export const flags: {
    [name: string]: string
} = {
    "albania": "🇦🇱",
    "armenia": "🇦🇲",
    "argentina": "🇦🇷",
    "austria": "🇦🇹",
    "australia": "🇦🇺",
    "bosnia": "🇧🇦",
    "bangladesh": "🇧🇩",
    "belgium": "🇧🇪",
    "bulgaria": "🇧🇬",
    "brazil": "🇧🇷",
    "canada": "🇨🇦",
    "switzerland": "🇨🇭",
    "china": "🇨🇳",
    "colombia": "🇨🇴",
    "costa rica": "🇨🇷",
    "germany": "🇩🇪",
    "denmark": "🇩🇰",
    "estonia": "🇪🇪",
    "egypt": "🇪🇬",
    "spain": "🇪🇸",
    "finland": "🇫🇮",
    "france": "🇫🇷",
    "georgia": "🇬🇪",
    "greece": "🇬🇷",
    "croatia": "🇭🇷",
    "hungary": "🇭🇺",
    "indonesia": "🇮🇩",
    "ireland": "🇮🇪",
    "israel": "🇮🇱",
    "india": "🇮🇳",
    "italy": "🇮🇹",
    "japan": "🇯🇵",
    "morocco": "🇲🇦",
    "mexico": "🇲🇽",
    "nigeria": "🇳🇬",
    "netherlands": "🇳🇱",
    "norway": "🇳🇴",
    "nepal": "🇳🇵",
    "new zealand": "🇳🇿",
    "pakistan": "🇵🇰",
    "poland": "🇵🇱",
    "portugal": "🇵🇹",
    "romania": "🇷🇴",
    "russia": "🇷🇺",
    "sweden": "🇸🇪",
    "slovenia": "🇸🇮",
    "slovakia": "🇸🇰",
    "tunisia": "🇹🇳",
    "turkey": "🇹🇷",
    "ukraine": "🇺🇦",
    "united states": "🇺🇸",
    "vietnam": "🇻🇳"
}